apiVersion: apps/v1
kind: Deployment
metadata:
  name: welcome-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: welcome-pod
  template:
    metadata:
      labels:
        app: welcome-pod
    spec:
      containers:
      - name: welcome-container
        image:${newImageName}
        ports:
        - containerPort: 8024
        resources:
          limits:
            cpu: "1000m"
            memory: "1000Mi"
          requests:
            cpu: "300m"
            memory: "300Mi
